[server]
headless = true
port = 8501
enableCORS = false
address = "0.0.0.0"

[theme]
base="dark"
primaryColor="#4ADEDE"
backgroundColor="#1E1E2F"
secondaryBackgroundColor="#2A2A40"
textColor="#F8F8F2"
font="sans serif"